---
- name: HTTPD. Install packages
  yum:
    name: "{{ yum_http_packages }}"
    state: present
  tags:
  - tests

- name: HTTPD. Remove welcome file
  file:
    path: "/etc/httpd/conf.d/welcome.conf"
    state: absent

- name: HTTPD. Enable and start service
  service:
    name: httpd
    state: started
    enabled: yes

- name: HTTPD. Enable firewall port
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
  tags:
  - tests
- name: HTTPD. reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
  tags:
  - tests

